### ISSUE TITLE
Some question about paper

### ISSUE THREAD

**Issue by root29** [victorprad/InfiniTAM#104]
Is splicing multiple small scenes into one big scene offline?
Isn't it possible to splice multiple small scenes into one big scene in real time online?
Thanks for your great works!

**Comment by sgolodetz** [comment]
You can, yes - e.g. you can run the relocalisations between the sub-scenes on a background thread / secondary GPU. You have to be careful to leave enough time between relocalisation attempts for relocaliser training to happen though, otherwise your relocalisers won't be trained. What have you tried? What problems are you experiencing?

**Comment by root29** [comment]
I tried multiple Xtions to recreate different scenes, and relocate their positions and splice them in real time online. Is this possible?
@sgolodetz

**Comment by sgolodetz** [comment]
With caveats - one key caveat being that our collaborative pipeline in `spaint` requires high-quality tracking within each sub-scene to perform well, which ICP isn't able to provide. We've been using Asus ZenFone ARs as our clients for interactive collaboration, which use visual-inertial odometry to provide good tracking. With Xtions and ICP, you're likely to get dubious results. A second caveat concerns what you mean by splicing them in real time online - in our approach, we keep the sub-scenes separate once they've been relocalised against each other, we don't merge them online. We do support offline merging (using the relative poses we've estimated) after the fact. What code are you using to do this though? Our code for that paper hasn't been released, so are you using something else?
