### ISSUE TITLE
How to run the surfel-based reconstruction with InfiniTAM v3

### ISSUE THREAD

**Issue by AIBluefisher** [victorprad/InfiniTAM#110]
Hi, @sgolodetz 

I have read the paper posted on arxiv: "InfiniTAM v3: A Framework for Large-Scale 3D Reconstruction with Loop Closure", and I build InfiniTAM v3 successfully. In section 7.3 and figure 8 of the paper, it shows InfiniTAM v3 can perform surfel-based reconstruction. But I don't know how to perform it. May you tell me?

Thank you very much!

**Comment by sgolodetz** [comment]
Add this to `InfiniTAM.cpp` before the mode switch:

    internalSettings->libMode = ITMLibSettings::LIBMODE_BASIC_SURFELS;

**Comment by AIBluefisher** [comment]
You are right, and I read some part of the code. 
But there still remains a problem: when reconstruction going on at a time,   the window shows nothing but the background.
![_002](https://user-images.githubusercontent.com/18096136/45279350-7b1fa180-b503-11e8-8f56-a8918633470f.png)
Besides, the surfel reconstruction is not same as the result of your paper. My result is shown below:
![_001](https://user-images.githubusercontent.com/18096136/45279394-938fbc00-b503-11e8-8bfd-6c7af03c4666.png)
and the result showed in your paper:
![_003](https://user-images.githubusercontent.com/18096136/45279459-c2a62d80-b503-11e8-80b4-56a10c05d870.png)
As it shows, your results can reconstruct the screen, but mine cannot. What's the problem?

**Comment by sgolodetz** [comment]
At a guess (it's been a while since I looked at the code), we might be using different settings for the unstable surfel rendering mode. Try setting USR_DONOTRENDER to USR_FAUTEDEMIEUX in ITMBasicSurfelEngine.tpp.

The setting controls whether or not to render the closest surfel found along each ray, regardless of confidence, if no confident one otherwise exists along the ray.

The ones on the screen are possibly less confident, and by default the setting is not to render anything along a ray if there isn't a confident one to be found. When I made the picture in the tech report, it looks like I was using the other setting (which is also why the colours on the desk look different in mine).

**Comment by sgolodetz** [comment]
The reason for the delay in showing anything when reconstruction starts is that initially there aren't any stable surfels to show - it takes time to build up confidence.

**Comment by AIBluefisher** [comment]
You may misunderstood what I say. At the beginning, the reconstruction behaves normal, but when it goes on for a while, the window shows nothing but the background.

**Comment by sgolodetz** [comment]
Sounds like a bug might have been introduced in that case - I'll investigate.

**Comment by AIBluefisher** [comment]
Thank you very much. I'm also going to figure out what's wrong.

**Comment by sgolodetz** [comment]
@AIBluefisher: Ok, problem solved :) You need to set the `libMode` in `ITMLibSettings.cpp`, not `main`, because there's a test lower down that changes the tracker config based on it (you need `framesToWeight` to be `1` for surfel tracking). It doesn't happen in `spaint`, because that hard-codes the tracker parameters separately in `TrackerFactory`. Yikes.

**Comment by sgolodetz** [comment]
The reason this didn't crop up before is that I originally only used the surfel engine in `spaint`, and the version in `InfiniTAM` itself was added as an afterthought. I haven't used it since it was merged, so I'd forgotten how to get it working :)

**Comment by sgolodetz** [comment]
p.s. Thanks to @tcavallari for remembering this!

**Comment by AIBluefisher** [comment]
It's working now. Thanks again!
