### ISSUE TITLE
Global view for iterating map reconstruction

### ISSUE THREAD

**Issue by kuonangzhe** [victorprad/InfiniTAM#98]
Awesome work! 

Are there any idea for showing iterating the process during map reconstruction, from a global view? Currently it is hard to see if there is drift or misalignment out of the front view.  

Thanks a lot!

**Comment by wangarad** [comment]
Hi @kuonangzhe,

you can press 'n' to process the first frame of your dataset (so that you have a sense of scale), then press `f` (free viewpoint) which puts you in the global view and after that you can manipulate the camera view (via the left, right and middle mouse buttons for rotation, translation and "zoom" respectively).

Once you are happy with your view into the scene, you can press 'b' to start the continuous reconstruction (of course, you can pause the reconstruction any time by pressing 'n').

**Comment by kuonangzhe** [comment]
@wangarad Thanks for the help! This can be a nice choice~

If anyone has idea for this, updating the issue anytime is welcome!
